######################## 配置spring的基本信息#######################################
spring:
  datasource:                ## 配置数据源
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.105.123.197:3306/es
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 6000
    minEvictableIdleTimeMillis: 25200000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    validationQuery: SELECT 1 FROM DUAL
    RemoveAbandanded: true
    removeAbandonedTimeout: 1800
    logAbandoned: true

  http:
    encoding:                # 配置POST中文乱码
      charset: UTF-8
      enabled: true
      force: true

  servlet:
    multipart:
      max-file-size: 200MB   # 限制一次上传的单个文件的总大小
      max-request-size: 500MB   # 限制一次上传的所有文件的总大小


############################## server的配置信息 ###################################
server:
  port: 8080                    # 配置访问的端口号
  servlet:
    context-path: /es-server    # 配置发布的项目名称
  tomcat:
    uri-encoding: UTF-8         #配置tomcat的编码格式，用于处理get请求的乱码问题




######################### mybatis的配置信息 ######################################

mybatis:
  # 指定mapper配置文件的位置
  mapper-locations: classpath:/mappers/*.xml
#  configuration:
#    map-underscore-to-camel-case: true   # 启用驼峰方式




######################### Redis的配置信息  #################################################




######################### es的配置信息  #################################################




















